export type Screen = 
  | 'onboarding' 
  | 'registration' 
  | 'chat-list' 
  | 'chat-room' 
  | 'search' 
  | 'create-group' 
  | 'business-profile' 
  | 'catalog' 
  | 'product-details' 
  | 'name-store' 
  | 'wallet' 
  | 'subscription'
  | 'notifications'
  | 'profile'
  | 'cloudflare-config';
